//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Requests
{
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    
    public class V3ActivateIdentityRequest
    {

        /// <summary>
        /// A Prove-generated unique ID for a specific identity.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=identityId")]
        public string IdentityId { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Models.Components.V3ActivateIdentityRequest? V3ActivateIdentityRequestValue { get; set; }
    }
}