//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectMobileClaim
    {

        /// <summary>
        /// MobileNumber will be used when performing OTP fallback and will not use the optional value provided by the SDK.<br/>
        /// 
        /// <remarks>
        /// Mobile number may be prefixed with a plus sign, but does not need to be for US. A plus sign is required for<br/>
        /// international.
        /// </remarks>
        /// </summary>
        [JsonProperty("mobileNumber")]
        public string? MobileNumber { get; set; }
    }
}