//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    
    public class AuthFinishResponseSubjects
    {

        [JsonProperty("card")]
        public AuthFinishResponseSubjectCardsResult? Card { get; set; }

        [JsonProperty("device")]
        public AuthFinishResponseSubjectDeviceResult? Device { get; set; }

        [JsonProperty("mobile")]
        public AuthFinishResponseSubjectMobileResult? Mobile { get; set; }

        [JsonProperty("user")]
        public AuthFinishResponseSubjectUserResult? User { get; set; }
    }
}