//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectMobileAuthenticators
    {

        [JsonProperty("instant")]
        public AuthStartRequestSubjectMobileAuthenticatorInstant? Instant { get; set; }

        [JsonProperty("instantlink")]
        public AuthStartRequestSubjectMobileAuthenticatorInstantLink? Instantlink { get; set; }

        [JsonProperty("otp")]
        public AuthStartRequestSubjectMobileAuthenticatorOTP? Otp { get; set; }

        [JsonProperty("passive")]
        public AuthStartRequestSubjectMobileAuthenticatorPassive? Passive { get; set; }

        [JsonProperty("universal")]
        public AuthStartRequestSubjectMobileAuthenticatorUniversal? Universal { get; set; }
    }
}