//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class AuthStartRequestSubjectCardAuthenticatorAirKeyClaim
    {

        /// <summary>
        /// Optional comma-separated list of PUIDs associated with the cardholder.
        /// </summary>
        [JsonProperty("puids")]
        public List<string>? Puids { get; set; }
    }
}