//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthFinishResponseSubjectDeviceResultSuccessClaim
    {

        /// <summary>
        /// DeviceID is the unique ID of the device.
        /// </summary>
        [JsonProperty("deviceId")]
        public string DeviceId { get; set; } = default!;
    }
}