//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectMobileAuthenticatorInstantLink
    {

        /// <summary>
        /// If AllowMobileNumberRePrompt is true, the end user will have up to 3 attempts<br/>
        /// 
        /// <remarks>
        /// to re-enter their phone number during a Prove Auth flow.<br/>
        /// If false, the end user won&apos;t be able to provide a new phone number.
        /// </remarks>
        /// </summary>
        [JsonProperty("allowMobileNumberRePrompt")]
        public bool? AllowMobileNumberRePrompt { get; set; }

        /// <summary>
        /// FinalTargetURL is the destination the end user will be directed to after clicking on the Instant Link.<br/>
        /// 
        /// <remarks>
        /// This is where we redirect the session upon successful authentication.
        /// </remarks>
        /// </summary>
        [JsonProperty("finalTargetUrl")]
        public string FinalTargetUrl { get; set; } = default!;

        /// <summary>
        /// MessageText is the message that will be sent to the end user via SMS with the Instant Link represented by pound signs.
        /// </summary>
        [JsonProperty("messageText")]
        public string MessageText { get; set; } = default!;

        /// <summary>
        /// SourceIP is the IP address of the device the request initiates from. This adds an additional fraud detection<br/>
        /// 
        /// <remarks>
        /// indicator, as Prove uses this value to complete an IP comparison with the IP of the device that clicks on<br/>
        /// the Instant Link sent. If provided, an IP match is required for a successful bind.
        /// </remarks>
        /// </summary>
        [JsonProperty("sourceIp")]
        public string? SourceIp { get; set; }

        /// <summary>
        /// SubscriptionCustomerID is a unique identifier for the customer&apos;s subscribers for Prove Identity Manager.
        /// </summary>
        [JsonProperty("subscriptionCustomerId")]
        public string? SubscriptionCustomerId { get; set; }

        [JsonProperty("testMode")]
        public string? TestMode { get; set; }
    }
}