//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;

    public class AuthenticationResults
    {
        /// <summary>
        /// An indication of the last authentication method used when the Prove Key was created.
        /// </summary>
        [JsonProperty("keySource")]
        public string? KeySource { get; set; }

        /// <summary>
        /// An indication of which mobile authentication method was used.
        /// </summary>
        [JsonProperty("mobile")]
        public string? Mobile { get; set; }
    }
}