//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectDeviceAuthenticatorPassive
    {

        /// <summary>
        /// AllowPasscodeFallback specifies whether passcode is allowed as a fallback protection for device in-app step-up keys.
        /// </summary>
        [JsonProperty("allowPasscodeFallback")]
        public bool? AllowPasscodeFallback { get; set; }

        /// <summary>
        /// UserVerificationLevel accepts &apos;required&apos;, &apos;preferred&apos; or &apos;discouraged&apos; as a value to specify biometric verification with FIDO.
        /// </summary>
        [JsonProperty("userVerificationLevel")]
        public string? UserVerificationLevel { get; set; }
    }
}