//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectMobileAuthenticatorOTP
    {

        /// <summary>
        /// If AllowMobileNumberRePrompt is true, the end user will have up to 3 attempts<br/>
        /// 
        /// <remarks>
        /// to re-enter their phone number during a Prove Auth flow.<br/>
        /// If false, the end user won&apos;t be able to provide a new phone number.
        /// </remarks>
        /// </summary>
        [JsonProperty("allowMobileNumberRePrompt")]
        public bool? AllowMobileNumberRePrompt { get; set; }

        /// <summary>
        /// If AllowOtpRetry is set to true, the end user will have up to 3 OTP entry attempts in a Prove Auth flow. If<br/>
        /// 
        /// <remarks>
        /// false, the end user will only get 1 OTP attempt. Once the maximum number of attempts is reached, the auth flow<br/>
        /// will return an error.
        /// </remarks>
        /// </summary>
        [JsonProperty("allowOtpRetry")]
        public bool? AllowOtpRetry { get; set; }

        /// <summary>
        /// MessageText is the message that will be sent to end user with the one-time passcode (OTP) represented by pound<br/>
        /// 
        /// <remarks>
        /// signs. The number of pound signs should be equal to the OTP length
        /// </remarks>
        /// </summary>
        [JsonProperty("messageText")]
        public string MessageText { get; set; } = default!;

        [JsonProperty("testMode")]
        public string? TestMode { get; set; }
    }
}