//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class AuthStartRequestSubjectMobileAuthenticatorUniversal
    {

        /// <summary>
        /// FinalTargetURL is the customer server URL that will be called back by Prove&apos;s Web page<br/>
        /// 
        /// <remarks>
        /// after UPK registration/verification ceremony is done.
        /// </remarks>
        /// </summary>
        [JsonProperty("finalTargetUrl")]
        public string FinalTargetUrl { get; set; } = default!;

        [JsonProperty("testMode")]
        public string? TestMode { get; set; }
    }
}