//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class Business
    {

        [JsonProperty("businessAddress")]
        public BusinessAddress? BusinessAddress { get; set; }

        [JsonProperty("businessName")]
        public string? BusinessName { get; set; }

        [JsonProperty("registrationFiling")]
        public RegistrationFiling? RegistrationFiling { get; set; }

        [JsonProperty("relatedPersons")]
        public List<RelatedPerson>? RelatedPersons { get; set; }

        [JsonProperty("taxId")]
        public string? TaxId { get; set; }

        [JsonProperty("tradeName")]
        public string? TradeName { get; set; }
    }
}