//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class DataSourceInternal
    {

        [JsonProperty("address")]
        public DataSourceAddressResponseInternal? Address { get; set; }

        [JsonProperty("cipConfidence")]
        public string? CipConfidence { get; set; }

        [JsonProperty("email")]
        public DataSourceEmailAddressResponseInternal? Email { get; set; }

        [JsonProperty("identifiers")]
        public DataSourceIdentifiersResponseInternal? Identifiers { get; set; }

        [JsonProperty("name")]
        public DataSourceNameResponseInternal? Name { get; set; }

        [JsonProperty("reasonCodes")]
        public List<string>? ReasonCodes { get; set; }
    }
}