//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class Identity
    {

        /// <summary>
        /// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
        /// </summary>
        [JsonProperty("assuranceLevel")]
        public string AssuranceLevel { get; set; } = default!;

        /// <summary>
        /// The input first name.
        /// </summary>
        [JsonProperty("firstName")]
        public string? FirstName { get; set; }

        /// <summary>
        /// The input last name.
        /// </summary>
        [JsonProperty("lastName")]
        public string? LastName { get; set; }

        /// <summary>
        /// Codes explaining the verification outcome
        /// </summary>
        [JsonProperty("reasons")]
        public List<string> Reasons { get; set; } = default!;
    }
}