//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class LinkedAccount
    {

        [JsonProperty("customerName")]
        public string? CustomerName { get; set; }

        [JsonProperty("proveAccountId")]
        public string? ProveAccountId { get; set; }

        [JsonProperty("proveId")]
        public string? ProveId { get; set; }
    }
}