//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class SubjectDeviceResultSuccessExtrasTrust
    {

        /// <summary>
        /// ReasonCodes contains a list of the reason codes detected on the device.
        /// </summary>
        [JsonProperty("reasonCodes")]
        public List<long>? ReasonCodes { get; set; }
    }
}