//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3ChallengeResponse
    {

        /// <summary>
        /// The evaluation result for the policy
        /// </summary>
        [JsonProperty("evaluation")]
        public Dictionary<string, Evaluation>? Evaluation { get; set; }

        [JsonProperty("individual")]
        public V3ChallengeIndividualRequest? Individual { get; set; }

        /// <summary>
        /// The next set of allowed calls in the same flow.
        /// </summary>
        [JsonProperty("next")]
        public Dictionary<string, string> Next { get; set; } = default!;

        /// <summary>
        /// True if the challenge was accepted and user info retrieved.
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; } = default!;
    }
}