//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3CompleteResponse
    {

        [JsonProperty("idv")]
        public IDVDataInternal? Idv { get; set; }

        [JsonProperty("kyc")]
        public KYCInternal? Kyc { get; set; }

        /// <summary>
        /// Next contains the next set of allowed calls in the same flow.
        /// </summary>
        [JsonProperty("next")]
        public Dictionary<string, string> Next { get; set; } = default!;

        /// <summary>
        /// Success returns true if the individual was verified successfully.
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; } = default!;
    }
}