//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3CompleteIndividualRequest
    {

        /// <summary>
        /// Address of the individual. Note that though this is an array, only the first address in the array will be processed.
        /// </summary>
        [JsonProperty("addresses")]
        public List<V3CompleteAddressEntryRequest>? Addresses { get; set; }

        /// <summary>
        /// The date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol &apos;-&apos;.
        /// </summary>
        [JsonProperty("dob")]
        public string? Dob { get; set; }

        /// <summary>
        /// Email address of the individual. Note that though this is an array, only the first email address in the array will be processed.
        /// </summary>
        [JsonProperty("emailAddresses")]
        public List<string>? EmailAddresses { get; set; }

        /// <summary>
        /// The first name of the individual.
        /// </summary>
        [JsonProperty("firstName")]
        public string? FirstName { get; set; }

        /// <summary>
        /// The last name of the individual.
        /// </summary>
        [JsonProperty("lastName")]
        public string? LastName { get; set; }

        /// <summary>
        /// The social security number of the individual.
        /// </summary>
        [JsonProperty("ssn")]
        public string? Ssn { get; set; }
    }
}