//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Response body for the V3 Identity Cross Domain API.
    /// </summary>
    public class V3CrossDomainIdentityResponse
    {

        /// <summary>
        /// The number of items in the Identities array.
        /// </summary>
        [JsonProperty("count")]
        public long Count { get; set; } = default!;

        /// <summary>
        /// The list of identities from other linked accounts.
        /// </summary>
        [JsonProperty("identites")]
        public List<IdentityItem> Identites { get; set; } = default!;
    }
}