//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    /// <summary>
    /// Response body for the V3 Enroll Identity method.
    /// </summary>
    public class V3EnrollIdentityResponse
    {

        /// <summary>
        /// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
        /// </summary>
        [JsonProperty("identityId")]
        public string IdentityId { get; set; } = default!;

        /// <summary>
        /// If true, the request was successful and the identity was created.
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; } = default!;
    }
}