//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    /// <summary>
    /// Response body for the Identity API GET method.
    /// </summary>
    public class V3GetIdentityResponse
    {

        /// <summary>
        /// If true, the identity is currently active.
        /// </summary>
        [JsonProperty("active")]
        public bool? Active { get; set; }

        /// <summary>
        /// The carrier associated with this identity/mobile number.
        /// </summary>
        [JsonProperty("carrier")]
        public string? Carrier { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific customer. This can be used by clients to link calls related to the same customer, across different requests or sessions.  The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
        /// </summary>
        [JsonProperty("clientCustomerId")]
        public string? ClientCustomerId { get; set; }

        /// <summary>
        /// The country code associated with the customer/identity. This will be in the ISO 3166-1 A-2 format.
        /// </summary>
        [JsonProperty("countryCode")]
        public string? CountryCode { get; set; }

        /// <summary>
        /// The time that this identity was created, in seconds since the Unix epoch.
        /// </summary>
        [JsonProperty("createdAt")]
        public long? CreatedAt { get; set; }

        /// <summary>
        /// The time that this identity was created, in ISO 8601 format.
        /// </summary>
        [JsonProperty("creationString")]
        public string? CreationString { get; set; }

        /// <summary>
        /// A string that is the unique identifier for the Prove Key on the device. Only applicable if you are leveraging Prove Unify.
        /// </summary>
        [JsonProperty("deviceId")]
        public string? DeviceId { get; set; }

        /// <summary>
        /// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
        /// </summary>
        [JsonProperty("identityId")]
        public string? IdentityId { get; set; }

        /// <summary>
        /// The type of line associated with this identity/mobile number.
        /// </summary>
        [JsonProperty("lineType")]
        public string? LineType { get; set; }

        /// <summary>
        /// The number of the mobile phone. Refer to the Prove Pre-Fill with Mobile Auth and Prove Identity with Mobile Auth documentation for situations where this field is not required. US phone numbers can be passed in with or without a leading +1. Acceptable characters are: alphanumeric with symbols &apos;+&apos;.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;
    }
}