//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Prove.Proveapi.Utils;
    
    public class V3TokenRequest
    {

        /// <summary>
        /// The client ID retrieved from the <a href="https://developer.prove.com/reference/authentication">Developer Portal</a>.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_id")]
        public string ClientId { get; set; } = default!;

        /// <summary>
        /// The client secret retrieved from the <a href="https://developer.prove.com/reference/authentication">Developer Portal</a>.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_secret")]
        public string ClientSecret { get; set; } = default!;

        /// <summary>
        /// The grant type. This field only accepts `client_credentials`.
        /// </summary>
        [SpeakeasyMetadata("form:name=grant_type")]
        public string GrantType { get; set; } = default!;
    }
}