//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class V3TokenResponse
    {

        /// <summary>
        /// The access token used to authenticate API calls.
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; set; } = default!;

        /// <summary>
        /// The lifetime of the token in seconds.
        /// </summary>
        [JsonProperty("expires_in")]
        public long ExpiresIn { get; set; } = default!;

        /// <summary>
        /// The lifetime of the refresh token in seconds. Not currently supported.
        /// </summary>
        [JsonProperty("refresh_expires_in")]
        public long? RefreshExpiresIn { get; set; }

        /// <summary>
        /// The token used to refresh the expiration time. Not currently supported.
        /// </summary>
        [JsonProperty("refresh_token")]
        public string? RefreshToken { get; set; }

        /// <summary>
        /// The type of token.
        /// </summary>
        [JsonProperty("token_type")]
        public string TokenType { get; set; } = default!;
    }
}