//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class V3UnifyRequest
    {

        /// <summary>
        /// If true, the customer can re-enter the OTP pin up to three times. Code must also be implemented. See client-side SDK guide for more details.
        /// </summary>
        [JsonProperty("allowOTPRetry")]
        public bool? AllowOTPRetry { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific customer.
        /// </summary>
        [JsonProperty("clientCustomerId")]
        public string? ClientCustomerId { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
        /// </summary>
        [JsonProperty("clientRequestId")]
        public string? ClientRequestId { get; set; }

        /// <summary>
        /// The URL where the end user will be redirected at the end of Instant Link flow. Required when `possessionType=desktop`.<br/>
        /// 
        /// <remarks>
        /// Acceptable characters are: alphanumeric with symbols &apos;-._+=/:?&apos;.
        /// </remarks>
        /// </summary>
        [JsonProperty("finalTargetUrl")]
        public string? FinalTargetUrl { get; set; }

        /// <summary>
        /// The mobile phone number. US phone numbers can be passed in with or without a leading `+1`. International phone numbers require a leading `+1`. Use the appropriate endpoint URL based on the region the number originates from. Acceptable characters are: alphanumeric with symbols &apos;+&apos;.<br/>
        /// 
        /// <remarks>
        /// Required unless Mobile Auth is enabled.
        /// </remarks>
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// The type of device being used - either `desktop` if using a desktop,<br/>
        /// 
        /// <remarks>
        /// `mobile` for iOS/Android native apps and mobile web, or `none` if no possession<br/>
        /// check is required.
        /// </remarks>
        /// </summary>
        [JsonProperty("possessionType")]
        public string PossessionType { get; set; } = default!;

        /// <summary>
        /// If `true`, rebinds the Prove Key with the newly verified phone number.
        /// </summary>
        [JsonProperty("rebind")]
        public bool? Rebind { get; set; }

        /// <summary>
        /// The message body sent in the Instant Link (`flowType=desktop`) or OTP (`flowType=mobile`) SMS message. If not provided, the following default messages will be used:<br/>
        /// 
        /// <remarks>
        /// Instant Link: &quot;Complete your verification. If you did not make this request, do not click the link. ####&quot; The verification URL replaces ####.<br/>
        /// OTP: &quot;#### is your temporary code to continue your application. Caution: for your security, don&apos;t share this code with anyone.&quot; Use ####, #####, or ###### to generate 4-6 digit verification codes respectively.<br/>
        /// Default language is English. Max length is 160 characters. Non-ASCII characters are allowed.
        /// </remarks>
        /// </summary>
        [JsonProperty("smsMessage")]
        public string? SmsMessage { get; set; }
    }
}