//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;

    public class V3UnifyStatusResponse
    {
        /// <summary>
        /// A client-generated unique ID to identify a specific customer across business lines.<br/>
        /// Required if success=true.
        /// </summary>
        [JsonProperty("clientHumanId")]
        public string? ClientHumanId { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific session. This can be used to identify specific requests.<br/>
        /// The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.<br/>
        /// Do not include Personally Identifiable Information (PII) in this field.
        /// </summary>
        [JsonProperty("clientRequestId")]
        public string? ClientRequestId { get; set; }

        /// <summary>
        /// The unique identifier for the Prove Key on the device.<br/>
        /// Required if success=true.
        /// </summary>
        [JsonProperty("deviceId")]
        public string? DeviceId { get; set; }

        /// <summary>
        /// The evaluation result for the policy. This will contain keys titled "authentication" and "risk" that encompass the different evaluation categories.
        /// </summary>
        [JsonProperty("evaluation")]
        public Dictionary<string, V3UnifyStatusResponseEvaluation>? Evaluation { get; set; }

        /// <summary>
        /// The number of the mobile phone used during the process.<br/>
        /// <br/>
        /// Required except when MobileAuth is used in US or a valid ProveID is provided.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// A unique ID to identify a specific customer obtained from a successful possession check.<br/>
        /// If an existing value is available (e.g. from a previous successful possession check) then it should be returned, otherwise a new value should be generated if success=true.<br/>
        /// Required if success=true.
        /// </summary>
        [JsonProperty("proveId")]
        public string? ProveId { get; set; }

        /// <summary>
        /// The result of the possession check.<br/>
        /// Possible values are `true`, `false`, `pending`, and `possession_required`.
        /// </summary>
        [JsonProperty("success")]
        public string Success { get; set; } = default!;
    }
}