//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class V3UnifyStatusResponse
    {

        /// <summary>
        /// The number of the mobile phone used during the process.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;

        [JsonProperty("success")]
        public string Success { get; set; } = default!;
    }
}