//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3UnifyBindResponse
    {

        /// <summary>
        /// The evaluation result for the policy
        /// </summary>
        [JsonProperty("evaluation")]
        public Dictionary<string, V3UnifyBindResponseEvaluation>? Evaluation { get; set; }

        /// <summary>
        /// The number of the mobile phone used during the process.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;

        /// <summary>
        /// The result of the possession check.<br/>
        /// 
        /// <remarks>
        /// Possible values are `true`, `false`, `pending`, and `possession_required`.
        /// </remarks>
        /// </summary>
        [JsonProperty("success")]
        public string Success { get; set; } = default!;
    }
}