//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    
    public class V3UnifyResponse
    {

        /// <summary>
        /// The one-time use JWT for the client-side SDK.
        /// </summary>
        [JsonProperty("authToken")]
        public string? AuthToken { get; set; }

        /// <summary>
        /// The unique ID that Prove generates for the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow - it cannot be reused outside of a single flow.
        /// </summary>
        [JsonProperty("correlationId")]
        public string CorrelationId { get; set; } = default!;

        /// <summary>
        /// The status of the Unify request.
        /// </summary>
        [JsonProperty("success")]
        public Success Success { get; set; } = default!;
    }
}