//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    
    public class V3UnifyRequest
    {

        /// <summary>
        /// If true, the customer can re-enter the OTP up to three times. Code must also be implemented. See client-side SDK guide for more details.
        /// </summary>
        [JsonProperty("allowOTPRetry")]
        public bool? AllowOTPRetry { get; set; }

        /// <summary>
        /// If true, TrustScore verification will be performed.
        /// </summary>
        [JsonProperty("checkReputation")]
        public bool? CheckReputation { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific customer.
        /// </summary>
        [JsonProperty("clientCustomerId")]
        public string? ClientCustomerId { get; set; }

        /// <summary>
        /// A client-generated unique ID to identify a specific customer across business lines.
        /// </summary>
        [JsonProperty("clientHumanId")]
        public string? ClientHumanId { get; set; }

        /// <summary>
        /// A client-generated unique ID for a specific session. This can be used to identify specific requests.<br/>
        /// 
        /// <remarks>
        /// The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.<br/>
        /// Do not include Personally Identifiable Information (PII) in this field.
        /// </remarks>
        /// </summary>
        [JsonProperty("clientRequestId")]
        public string ClientRequestId { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the Prove Key on the device.
        /// </summary>
        [JsonProperty("deviceId")]
        public string? DeviceId { get; set; }

        /// <summary>
        /// The email address of the customer. Acceptable characters are: alphanumeric with symbols &apos;@.+&apos;.
        /// </summary>
        [JsonProperty("emailAddress")]
        public string? EmailAddress { get; set; }

        /// <summary>
        /// The URL where the end user will be redirected at the end of Instant Link flow. Required when `possessionType=desktop`.<br/>
        /// 
        /// <remarks>
        /// Acceptable characters are: alphanumeric with symbols &apos;-._+=/:?&apos;. Max length is 128 characters.
        /// </remarks>
        /// </summary>
        [JsonProperty("finalTargetUrl")]
        public string? FinalTargetUrl { get; set; }

        /// <summary>
        /// The IP address of the customer. Acceptable characters are: Alphanumeric with &apos;.:&apos; symbols.
        /// </summary>
        [JsonProperty("ipAddress")]
        public string? IpAddress { get; set; }

        /// <summary>
        /// The mobile phone number. US phone numbers can be passed in with or without a leading `+1`. International phone numbers require a leading `+1`. Use the appropriate endpoint URL based on the region the number originates from. Acceptable characters are: alphanumeric with symbols &apos;+&apos;.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Required except when MobileAuth is used in US or a valid ProveID is provided.
        /// </remarks>
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// The type of device being used - either `desktop` if using a desktop,<br/>
        /// 
        /// <remarks>
        /// `mobile` for iOS/Android native apps and mobile web, or `none` if no possession<br/>
        /// check is required.
        /// </remarks>
        /// </summary>
        [JsonProperty("possessionType")]
        public string PossessionType { get; set; } = default!;

        /// <summary>
        /// A unique ID to identify a specific customer obtained from a previous successful authentication.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Required if phoneNumber is not present and mobileAuth is not enabled in the US or phoneNumber is not present in the EU.
        /// </remarks>
        /// </summary>
        [JsonProperty("proveId")]
        public string? ProveId { get; set; }

        /// <summary>
        /// If `true`, rebinds the Prove Key with the newly verified phone number.
        /// </summary>
        [JsonProperty("rebind")]
        public bool? Rebind { get; set; }

        /// <summary>
        /// The message body sent in the Instant Link (`flowType=desktop`) or OTP (`flowType=mobile`) SMS message. If not provided, the following default messages will be used:<br/>
        /// 
        /// <remarks>
        /// Instant Link: &quot;Complete your verification. If you did not make this request, do not click the link. ####&quot; The verification URL replaces ####.<br/>
        /// OTP: &quot;#### is your temporary code to continue your application. Caution: for your security, don&apos;t share this code with anyone.&quot; Use ####, #####, or ###### to generate 4-6 digit verification codes respectively.<br/>
        /// Default language is English. Max length is 160 characters. Non-ASCII characters are allowed.
        /// </remarks>
        /// </summary>
        [JsonProperty("smsMessage")]
        public string? SmsMessage { get; set; }
    }
}