//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3ValidateResponse
    {

        /// <summary>
        /// Challenge missing returns true if a DOB or SSN needs to be passed in on the next step.
        /// </summary>
        [JsonProperty("challengeMissing")]
        public bool ChallengeMissing { get; set; } = default!;

        /// <summary>
        /// Next contains the next set of allowed calls in the same flow.
        /// </summary>
        [JsonProperty("next")]
        public Dictionary<string, string> Next { get; set; } = default!;

        /// <summary>
        /// PhoneNumber is the number of the mobile phone for which validation was performed.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// Success returns true if the phone number was validated.
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; } = default!;
    }
}