//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Prove.Proveapi.Utils;
    
    /// <summary>
    /// The result of the possession check. Possible values are `success`, `pending`, `failed`, and `not_applicable`.
    /// </summary>
    public class V3VerifyStatusResponsePossessionResult
    {
    }
}