//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    
    /// <summary>
    /// Response body for the V3 Verify Status API
    /// </summary>
    public class V3VerifyStatusResponse
    {

        /// <summary>
        /// Possession Result represents the result of the Possession check. Possible values are &quot;success&quot;, &quot;pending&quot;, &quot;failed&quot;, and &quot;not applicable&quot;.
        /// </summary>
        [JsonProperty("possessionResult")]
        public V3VerifyStatusResponsePossessionResult PossessionResult { get; set; } = default!;

        /// <summary>
        /// Success is the result of the combination of Verify Result and Possession Result. Possible values are &quot;true&quot;, &quot;pending&quot;, and &quot;false&quot;. The success value will be &quot;pending&quot; until the results of both Verify and Possession are returned or one of them fails, blocking the other.
        /// </summary>
        [JsonProperty("success")]
        public V3VerifyStatusResponseSuccess Success { get; set; } = default!;

        /// <summary>
        /// Verify Result represents the result of the Verify process. Possible values are &quot;success&quot;, &quot;pending&quot;, &quot;failed&quot;, and &quot;not applicable&quot;.
        /// </summary>
        [JsonProperty("verifyResult")]
        public V3VerifyStatusResponseVerifyResult VerifyResult { get; set; } = default!;
    }
}