//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3VerifyBatchRequest
    {

        /// <summary>
        /// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
        /// </summary>
        [JsonProperty("clientRequestId")]
        public string? ClientRequestId { get; set; }

        /// <summary>
        /// Batch of verify requests to process. The array length cannot exceed 1000 items.
        /// </summary>
        [JsonProperty("items")]
        public List<VerifyBatchRequestItem> Items { get; set; } = default!;
    }
}