//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;
    
    public class V3VerifyResponse
    {

        /// <summary>
        /// Additional Identities found as part of the verification flow.
        /// </summary>
        [JsonProperty("additionalIdentities")]
        public List<Models.Components.Identity>? AdditionalIdentities { get; set; }

        /// <summary>
        /// The input ClientCustomerID.
        /// </summary>
        [JsonProperty("clientCustomerId")]
        public string? ClientCustomerId { get; set; }

        /// <summary>
        /// The input ClientHumanID.
        /// </summary>
        [JsonProperty("clientHumanId")]
        public string? ClientHumanId { get; set; }

        /// <summary>
        /// The input ClientRequestID.
        /// </summary>
        [JsonProperty("clientRequestId")]
        public string? ClientRequestId { get; set; }

        /// <summary>
        /// The unique ID that Prove generates for the flow.
        /// </summary>
        [JsonProperty("correlationId")]
        public string CorrelationId { get; set; } = default!;

        /// <summary>
        /// The evaluation result for the policy. This will contain keys titled &quot;authentication&quot; and &quot;risk&quot; that encompass the different evaluation categories.
        /// </summary>
        [JsonProperty("evaluation")]
        public Dictionary<string, V3VerifyResponseEvaluation>? Evaluation { get; set; }

        [JsonProperty("identity")]
        public Models.Components.Identity? Identity { get; set; }

        /// <summary>
        /// The input phone number.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;

        /// <summary>
        /// A Prove-generated identifier for the consumer.
        /// </summary>
        [JsonProperty("proveId")]
        public string? ProveId { get; set; }

        /// <summary>
        /// A persistent ID that uniquely identifies a telephone subscriber.
        /// </summary>
        [JsonProperty("provePhoneAlias")]
        public string? ProvePhoneAlias { get; set; }

        /// <summary>
        /// The result of verification. This can be &quot;true&quot; or &quot;false&quot;.
        /// </summary>
        [JsonProperty("success")]
        public string Success { get; set; } = default!;
    }
}