//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System;
    
    /// <summary>
    /// The verification method based on the use case and authorization level. Current allowed values: &quot;verifiedUser&quot;, &quot;accountOpening&quot;, &quot;bot&quot;, &quot;prefill&quot;, &quot;prefillForBiz&quot;, &quot;identityResolution&quot;.
    /// </summary>
    public enum VerificationType
    {
        [JsonProperty("bot")]
        Bot,
        [JsonProperty("verifiedUser")]
        VerifiedUser,
        [JsonProperty("accountOpening")]
        AccountOpening,
        [JsonProperty("prefill")]
        Prefill,
        [JsonProperty("prefillForBiz")]
        PrefillForBiz,
        [JsonProperty("identityResolution")]
        IdentityResolution,
    }

    public static class VerificationTypeExtension
    {
        public static string Value(this VerificationType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static VerificationType ToEnum(this string value)
        {
            foreach(var field in typeof(VerificationType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is VerificationType)
                    {
                        return (VerificationType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum VerificationType");
        }
    }

}