//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Prove.Proveapi.Utils;
    
    /// <summary>
    /// Verify Result represents the result of the Verify process. Possible values are &quot;success&quot;, &quot;pending&quot;, and &quot;failed&quot;. If the Verify result is pending, clients will need to call the Verify Status API to get a result.
    /// </summary>
    public class VerifyResult
    {
    }
}