//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Components
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Models.Components;
    using Prove.Proveapi.Utils;
    using System.Collections.Generic;

    public class VerifyBatchResultItem
    {
        /// <summary>
        /// (required IF verificationType=VerifiedUser).
        /// </summary>
        [JsonProperty("additionalIdentities")]
        public List<Models.Components.Identity>? AdditionalIdentities { get; set; }

        /// <summary>
        /// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
        /// </summary>
        [JsonProperty("assuranceLevel")]
        public string AssuranceLevel { get; set; } = default!;

        /// <summary>
        /// The input ClientCustomerID.
        /// </summary>
        [JsonProperty("clientCustomerId")]
        public string ClientCustomerId { get; set; } = default!;

        /// <summary>
        /// The input ClientHumanID.<br/>
        /// (required IF verificationType=VerifiedUser).
        /// </summary>
        [JsonProperty("clientHumanId")]
        public string? ClientHumanId { get; set; }

        /// <summary>
        /// An error message for this corresponding specific verification.
        /// </summary>
        [JsonProperty("error")]
        public string? Error { get; set; }

        /// <summary>
        /// The evaluation result for the policy. This will contain keys titled "authentication" and "risk" that encompass the different evaluation categories.
        /// </summary>
        [JsonProperty("evaluation")]
        public Dictionary<string, VerifyBatchResultItemEvaluation>? Evaluation { get; set; }

        [JsonProperty("identity")]
        public Models.Components.Identity? Identity { get; set; }

        /// <summary>
        /// The input phone number.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;

        /// <summary>
        /// A Prove-generated identifier for the consumer.<br/>
        /// (required IF verificationType=VerifiedUser).
        /// </summary>
        [JsonProperty("proveId")]
        public string? ProveId { get; set; }

        /// <summary>
        /// A persistent ID that uniquely identifies a telephone subscriber.<br/>
        /// (required IF verificationType=VerifiedUser).
        /// </summary>
        [JsonProperty("provePhoneAlias")]
        public string? ProvePhoneAlias { get; set; }

        /// <summary>
        /// The result of verification. This can be "true" or "false".
        /// </summary>
        [JsonProperty("success")]
        public string Success { get; set; } = default!;
    }
}