//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Errors
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System;
    
    public class Error400 : Exception
    {

        /// <summary>
        /// An error code that describes the problem category of the request.
        /// </summary>
        [JsonProperty("code")]
        public long? Code { get; set; }

        /// <summary>
        /// The error message describing the problem with the request.
        /// </summary>
        [JsonProperty("message")]
        private string? _message { get; set; }
        public override string Message { get {return _message ?? "";} }
    }
}