//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Prove.Proveapi.Models.Errors
{
    using Newtonsoft.Json;
    using Prove.Proveapi.Utils;
    using System;
    using System.Net.Http;

    public class Error401Payload
    {
        /// <summary>
        /// An error code that describes the problem category of the request.
        /// </summary>
        [JsonProperty("code")]
        public long? Code { get; set; }

        /// <summary>
        /// The error message describing the problem with the request.
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }

    public class Error401 : ProveAPIError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public Error401Payload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error401.Payload.Code instead.")]
        public long? Code { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error401.Payload.Message instead.")]
        private string? _message { get; set; }

        private static string ErrorMessage(Error401Payload payload, string body)
        {
            string? message = payload.Message;
            if (!string.IsNullOrEmpty(message))
            {
                return message;
            }

            return "API error occurred";
        }

        public Error401(
            Error401Payload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base(ErrorMessage(payload, body), request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Code = payload.Code;
           _message = payload.Message;
           #pragma warning restore CS0618
        }
    }

}